### ISSUE TITLE
[Kahi_minciencias_opendata_person] Lots of warnings

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#219]
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  articulos.sort_values("year", inplace=True)
/home/ozapatam/.local/lib/python3.11/site-packages/kahi_minciencias_opendata_person/Kahi_minciencias_opendata_person.py:59: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

**Comment by fedevergara** [comment]
Solved in https://github.com/colav/Kahi_plugins/pull/228
