### ISSUE TITLE
[Scholar Person] to implement this plugin

### ISSUE THREAD

**Issue by grupocolav** [colav/Kahi_plugins#256]
have in mind that

'R Urrego': 'SCegeOUAAAAJ'  from bibtex is 
@article{urrego2014epigenetic,
  title={Epigenetic disorders and altered gene expression after use of assisted reproductive technologies in domestic cattle},
  author={**Urrego, Rodrigo** and Rodriguez-Osorio, N{\'e}lida and Niemann, Heiner},
  journal={Epigenetics},
  volume={9},
  number={6},
  pages={803--815},
  year={2014},
  publisher={Taylor \& Francis}
}

should be

{last_names: 'Urrego', "first_names":Rodrigo}  with id  'SCegeOUAAAAJ'

names such as N{\'e}lida 

have to be parsed by bibtexparser

**Comment by omazapa** [comment]
implemented with PR https://github.com/colav/Kahi_plugins/pull/296
