### ISSUE TITLE
Most of the DOIs of Scienti not processed 

### ISSUE THREAD

**Issue by restrepo** [colav/Kahi_plugins#67]
In the current ETL only 7188 of the total 18181 dois were processed with the scienti information. However most of the missing ones are really in scienti and not were used at all. A sample with 10,000 of the missing dois according to the Scienti API endpoint 2022 for UdeA:

http://apis.colav.co/scienti/info?apikey=XXXX&get=ids&institution=udea&model_year=2022

are in this JSON.

https://drive.google.com/file/d/1g0o1bohFQISFZCauOIVVMgVaXK67kX92/view?usp=sharing

The issue is maybe related to the preprocessing of the dois. They can have `http` or `https` and `doi.org` or dx.doi.org`, etc. Therefore a REGEX is necessary
```python
re.sub(r'https*\:\/\/[\w\.]+\/','',doi).lower()
```

**Comment by muzgash** [comment]
Fixed in commit [e4fbb18](https://github.com/colav/Kahi_plugins/commit/e4fbb187d617978962c67752c59863bea8e7eddd)
